### ISSUE TITLE
Ceremonias scrum:

### ISSUE THREAD

**Issue by JohaNA2805** [JohaNA2805/Proyecto-Colaborativo-2022-ISPC#3]
Desarrolla:

● Sprint Planning Meeting

● Daily Scrum Meeting

**Comment by MarielaGomez** [comment]
_**_¿Qué es la planificación de sprints?_**_
La planificación de sprints es un evento en scrum que inicia el sprint. El objetivo de la planificación de sprints es definir lo que se puede entregar en el sprint y cómo se conseguirá ese trabajo. La planificación de sprints se hace en colaboración con todo el equipo de scrum.
*****************
En  un periodo definido de tiempo en el que se hace todo el trabajo. Sin embargo, antes de poder ponerte manos a la obra tienes que preparar el sprint. Tienes que decidir cuánto tiempo va a durar, el objetivo del sprint y por dónde vas a empezar. La sesión de planificación de sprints inicia el sprint definiendo el orden del día y el punto de atención. Si se hace correctamente, también crea un entorno en el que el equipo está motivado, se siente retado y puede triunfar. Las malas planificaciones de sprints pueden fastidiar al equipo al definir expectativas no realistas.
------------------
Daily Scrum (Scrum Diario) --No son reuniones de reporte de estado al Scrum Master 
●Son compromisos frente a los demás miembros del equipo.
Sprint Review/Retrospective Sprint Review 
●El equipo presenta la funcionalidad terminada al Product Owner y demás stakeholders. 
●Los miembros del equipo responden preguntas de los stakeholders en relación a la demostración, y toman nota de los cambios propuestos. 
●Al finalizar la presentación, los stakeholders dan su impresión acerca del producto, cambios deseados y prioridad de esos cambios. Sprint Retrospective 
●Provee una visión de qué está funcionando y qué no está funcionando. 
●Se realiza al finalizar el sprint. 
●Participa todo el equipo. No es una reunión de seguimiento, la presentación del increme
