### ISSUE TITLE
-Artefactos de Scrum

### ISSUE THREAD

**Issue by JohaNA2805** [JohaNA2805/Proyecto-Colaborativo-2022-ISPC#5]
-Artefactos de Scrum
¿Cuáles son?

**Comment by ymgomez** [comment]
adjunto un archivo con la definición de los tres tipos de artefactos de SCRUM y una abreve definición de éste también.

dejo un link donde explican el tema para el que le sirva:
https://www.youtube.com/watch?v=eIoyIoKa7IE


[Artefactos de Scrum.docx](https://github.com/JohaNA2805/Proyecto-Colaborativo-2022-ISPC/files/8862922/Artefactos.de.Scrum.docx)
